.runner_template: &runner_definition
  tags: 
    - iinumbers-shell

stages:
  - rawdata
  - resample
  - featurize
  - lagging
  - joining
  - labeled

continues:TXF:
  stage: rawdata
  script: python test.py
  <<: *runner_definition
  
k:1min:
  stage: resample
  script: python test.py
  <<: *runner_definition
  
k:5min:
  stage: resample
  script: python test.py
  <<: *runner_definition
  
k:15min:
  stage: resample
  script: python test.py
  <<: *runner_definition
  
k:30min:
  stage: resample
  script: python test.py
  <<: *runner_definition
  
k:1hour:
  stage: resample
  script: python test.py
  <<: *runner_definition
  
sma:1min:
  stage: featurize
  script: python test.py
  <<: *runner_definition
  
