
stages:
  - resample
  - featurize
  - lagging
  - joining
  - labeled
  
k:1min:
  stage: resample
  script: python test.py
  tags:
    - iinumbers-shell
  
k:5min:
  stage: resample
  script: python test.py
  tags:
    - iinumbers-shell
